services:

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  flink-jobmanager:
    build:
      context: .
      dockerfile: Dockerfile.flink

    container_name: streamforge-flink-jobmanager

    command: /start-flink.sh

    ports:
      - "8081:8081"

    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager

    volumes:
      - ./flink_jobs:/opt/flink/jobs

    depends_on:
      - kafka

  flink-taskmanager:
    build:
      context: .
      dockerfile: Dockerfile.flink

    container_name: streamforge-flink-taskmanager

    command: taskmanager

    depends_on:
      - flink-jobmanager

    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager

    volumes:
      - ./flink_jobs:/opt/flink/jobs

  minio:
    image: minio/minio:latest

    command: server /data --console-address ":9001"

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer

    container_name: streamforge-producer

    depends_on:
      - kafka

    restart: unless-stopped

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer

    container_name: streamforge-consumer

    depends_on:
      - kafka

    restart: unless-stopped

  lstm:
    build:
      context: .
      dockerfile: Dockerfile.lstm

    container_name: streamforge-lstm

    depends_on:
      - kafka

    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile.dashboard

    container_name: streamforge-dashboard

    depends_on:
      - kafka

    ports:
      - "5000:5000"

    restart: unless-stopped